- id: dprint
  name: dprint
  description: "A pluggable and configurable code formatting platform written in Rust."
  entry: dprint fmt
  language: node
  "types": [text]
  args: []
  require_serial: false
  additional_dependencies: ["dprint@0.32.0"]
  minimum_pre_commit_version: "0"
