[[plugins]]
  package = "netlify-plugin-checklinks"

    [plugins.inputs]

    skipPatterns = ["#", "www.google-analytics.com", "www.googletagmanager.com","https://coveralls.io/repos/github/temporalio/temporal-go-sdk/badge.svg?branch=master", "/docs/typescript/client"]
    pretty = true

## Note: if you are looking for Redirects
# they have been moved to /static/_redirects to make it more manageable - swyx