[[plugins]]
  package = "netlify-plugin-checklinks"

    [plugins.inputs]

    skipPatterns = ["#!", "www.google-analytics.com", "www.googletagmanager.com", "#main"]
    pretty = true

[[redirects]]
  from = "/docs/overview"
  to = "/docs/concept-overview"

[[redirects]]
  from = "/docs/activities"
  to = "/docs/concept-activities"

[[redirects]]
  from = "/docs/workflows"
  to = "/docs/concept-workflows"

[[redirects]]
  from = "/docs/events"
  to = "/docs/signals"

[[redirects]]
  from = "/docs/concept-namespaces"
  to = "/docs/server-namespaces"

[[redirects]]
  from = "/docs/go-execute-activity"
  to = "/docs/go-activities#executing-activities"

[[redirects]]
  from = "/docs/go-activity-async-completion"
  to = "/docs/go-activities#asynchronous-activity-completion"

[[redirect]]
  from = "/docs/java-sdk-overview"
  to = "/docs/java-sdk-introduction"

[[redirect]]
  from = "/docs/go-sdk-overview"
  to = "/docs/go-sdk-introduction"

[[redirect]]
  from = "/docs/php-sdk-overview"
  to = "/docs/php-sdk-introduction"

[[redirect]]
  from = "/docs/sdks-introduction"
  to = "/application-development"

[[redirects]]
  from = "/docs/use-cases-actors"
  to = "https://temporal.io/usecases#Actors"

[[redirects]]
  from = "/docs/use-cases-distributed-transactions"
  to = "https://temporal.io/usecases#transactions"

[[redirects]]
  from = "/docs/use-cases-dsl"
  to = "https://temporal.io/usecases#DSL"

[[redirects]]
  from = "/docs/use-cases-long-running"
  to = "https://temporal.io/usecases#Processes"

[[redirects]]
  from = "/docs/use-cases-monitoring"
  to = "https://temporal.io/usecases#Monitoring"

[[redirects]]
  from = "/docs/use-cases-orchestration"
  to = "https://temporal.io/usecases#orchestration"

[[redirects]]
  from = "/docs/use-cases-pipelines"
  to = "https://temporal.io/usecases#Pipelines"

[[redirects]]
  from = "/docs/use-cases-provisioning"
  to = "https://temporal.io/usecases#provisioning"

[[redirects]]
  from = "/docs/get-started"
  to = "/"

[[redirects]]
  from = "/docs/go-workflow-testing"
  to = "/docs/go-testing"

#
# Server pages
#
[[redirects]]
  from = "/docs/server-archive-data"
  to = "/docs/server/archive-data"

[[redirects]]
  from = "/docs/server-configuration"
  to = "/docs/server/configuration"

[[redirects]]
  from = "/docs/server-elasticsearch-setup"
  to = "/docs/server/elasticsearch-setup"

[[redirects]]
  from = "/docs/server-event-types"
  to = "/docs/server/event-types"

[[redirects]]
  from = "/docs/server-introduction"
  to = "/docs/server/introduction"

[[redirects]]
  from = "/docs/server-namespaces"
  to = "/docs/server/namespaces"

[[redirects]]
  from = "/docs/server-options"
  to = "/docs/server/options"

[[redirects]]
  from = "/docs/server-production-deploy"
  to = "/docs/server/production-deploy"

[[redirects]]
  from = "/docs/server-quick-install"
  to = "/docs/server/quick-install"

[[redirects]]
  from = "/docs/server-security"
  to = "/docs/server/security"

[[redirects]]
  from = "/docs/server-versions-and-dependencies"
  to = "/docs/server/versions-and-dependencies"

[[redirects]]
  from = "/docs/server-workflow-search"
  to = "/docs/server/workflow-search"
