origins:
  - owner: temporalio
    repo: money-transfer-project-template-java
  - owner: temporalio
    repo: hello-world-project-template-java
  - owner: temporalio
    repo: money-transfer-project-template-go
  - owner: temporalio
    repo: hello-world-project-template-go
  - owner: temporalio
    repo: subscription-workflow-project-template-go
  - owner: temporalio
    repo: subscription-workflow-project-template-java
  - owner: temporalio
    repo: subscription-workflow-project-template-php
  - owner: temporalio
    repo: temporal
    ref: snipwrappers
  - owner: temporalio
    repo: samples-php
  - owner: temporalio
    repo: samples-node
  - owner: temporalio
    repo: samples-go
  - owner: temporalio
    repo: samples-java
  - owner: temporalio
    repo: temporal-ecommerce

targets:
  - docs
  - blog

features:
  enable_source_link: true
  enable_code_block: true
