origins:
  - owner: temporalio
    repo: temporal
  - owner: temporalio
    repo: samples-php
  - owner: temporalio
    repo: samples-typescript
  - owner: temporalio
    repo: samples-python
  - owner: temporalio
    repo: reference-app-orders-go
  # Some samples were left in the SDK code itself because it has better testing
  # capabilities than the samples repo
  - owner: temporalio
    repo: sdk-typescript
  - owner: temporalio
    repo: samples-go
  - owner: temporalio
    repo: samples-java
    ref: 'nexus-snip-sync'
  - owner: temporalio
    repo: reference-app-orders-go
  - files:
      pattern: './sample-apps/**/*.go'
      owner: 'temporalio'
      repo: 'documentation'
      ref: 'main'
  - files:
      pattern: './sample-apps/**/*.java'
      owner: 'temporalio'
      repo: 'documentation'
      ref: 'main'

targets:
  - docs

features:
  enable_source_link: true
  enable_code_block: true
