origins:
  - owner: temporalio
    repo: temporal
  - owner: temporalio
    repo: samples-php
  - owner: temporalio
    repo: samples-typescript
  - owner: temporalio
    repo: samples-python
  - owner: temporalio
    repo: reference-app-orders-go
  # Some samples were left in the SDK code itself because it has better testing
  # capabilities than the samples repo
  - owner: temporalio
    repo: sdk-typescript
  - owner: temporalio
    repo: samples-go
  - owner: temporalio
    repo: samples-ruby
  - owner: temporalio
    repo: samples-dotnet
  - owner: temporalio
    repo: samples-java
  - owner: temporalio
    repo: features
  - owner: temporalio
    repo: reference-app-orders-go
  # Money transfer project templates
  - owner: temporalio
    repo: money-transfer-project-template-dotnet
  - owner: temporalio
    repo: money-transfer-project-template-python
  - owner: temporalio
    repo: money-transfer-project-java
  - owner: temporalio
    repo: money-transfer-project-template-ts
  - owner: temporalio
    repo: money-transfer-project-template-go
  - owner: temporalio
    repo: money-transfer-project-template-php
  - owner: temporalio
    repo: money-transfer-project-template-ruby
  # Sample apps
  - files:
      pattern: './sample-apps/**/*.go'
      owner: 'temporalio'
      repo: 'documentation'
      ref: 'main'
  - files:
      pattern: './sample-apps/**/*.java'
      owner: 'temporalio'
      repo: 'documentation'
      ref: 'main'

targets:
  - docs

features:
  enable_source_link: true
  enable_code_block: true
