name: test adding an action

on: 
  # runs when any PR changes
  pull_request:

jobs:
  test-format:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        cache: 'yarn'

    # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
    - run: yarn install --frozen-lockfile

    - name: Run dprint
      run: npm run fmt

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4